
var MongoClient = require('mongodb').MongoClient
  , assert = require('assert');

var gensamp = require("./gensamp.js");

var p = console.log;


// Connection URL
//var dburl = 'mongodb://localhost:27017/myproject';
var dburl = 'mongodb://localhost:27017/ggsys';

//// Use connect method to connect to the server
//MongoClient.connect(dburl, function(err, db) {
//  assert.equal(null, err);
//  console.log("Connected successfully to server");
//
//  db.close();
//});


function valueCollection(callback){
    MongoClient.connect(dburl, function(err, db) {
        assert.equal(null, err);

        return callback(null, db.collection('value'));
    });
}


function get_one_value_rec(callback){
    valueCollection(function(err, col){
        if(err) return callback(err);

        col.findOne({parentid: {$exists: false}}, callback);
    });
}


module.exports.valueCollection = valueCollection;
module.exports.get_one_value_rec = get_one_value_rec;


// checkings 


/*
 * check to insert one sample data, it's value record,
 * random words generated by reading the 'shawshank redemption'
 */
function insertOne(){
    gensamp.genSample(function(err, sam){
        p(sam, err);

        valueCollection(function(err, vcoll){
            vcoll.insertOne(sam, function(err, what){
                p(Object.keys(what), err);
            });
        });
    });
}

function insert_one_sample_value_rec(callback){
    gensamp.genSample(function(err, sam){
        p(sam, err);

        valueCollection(function(err, vcoll){
            vcoll.insertOne(sam, callback);
        });
    });
}



function checkInsert(){
    for(var i = 0; i<10; i++){
        insert_one_sample_value_rec(function(){});
    }
}

function checkGetOne(){
    get_one_value_rec(function(err, what){
        p(what, err);
    });
}



if(require.main === module){

    //insertOne();
    //checkInsert();

    checkGetOne();

    setTimeout(()=>{
        process.exit();
    }, 3000);
}
